version: '3.4'

x-common:
  &common
  image: apache/airflow:2.3.4
  user: "${AIRFLOW_UID:-50000}:0"
  env_file: 
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models
    - /var/run/docker.sock:/var/run/docker.sock

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgres:
    image: postgres:13
    container_name: postgres-fp
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scheduler:
    <<: [*common, *depends-on]
    container_name: airflow-scheduler-fp
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=pydrive

  webserver:
    <<: [*common, *depends-on]
    container_name: airflow-webserver-fp
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=pydrive
  
  airflow-init:
    <<: *common
    container_name: airflow-init-fp
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version

volumes:
  postgres-data:
